"""Prompt templates for Insight and Strategic agents."""

from src.prompts.insight_prompt import INSIGHT_SYSTEM_PROMPT, INSIGHT_USER_TEMPLATE
from src.prompts.question_analyzer_prompt import QUESTION_ANALYZER_SYSTEM_PROMPT, QUESTION_ANALYZER_USER_TEMPLATE
from src.prompts.question_classifier_prompt import CLASSIFIER_SYSTEM_PROMPT, CLASSIFIER_USER_TEMPLATE
from src.prompts.risk_analysis_prompt import RISK_ANALYSIS_SYSTEM_PROMPT, RISK_ANALYSIS_USER_TEMPLATE
from src.prompts.strategic_planner_prompt import STRATEGIC_PLANNER_SYSTEM_PROMPT, STRATEGIC_PLANNER_USER_TEMPLATE
from src.prompts.synthesis_prompt import SYNTHESIS_SYSTEM_PROMPT, SYNTHESIS_USER_TEMPLATE

__all__ = [
    "QUESTION_ANALYZER_SYSTEM_PROMPT",
    "QUESTION_ANALYZER_USER_TEMPLATE",
    "INSIGHT_SYSTEM_PROMPT",
    "INSIGHT_USER_TEMPLATE",
    "CLASSIFIER_SYSTEM_PROMPT",
    "CLASSIFIER_USER_TEMPLATE",
    "STRATEGIC_PLANNER_SYSTEM_PROMPT",
    "STRATEGIC_PLANNER_USER_TEMPLATE",
    "RISK_ANALYSIS_SYSTEM_PROMPT",
    "RISK_ANALYSIS_USER_TEMPLATE",
    "SYNTHESIS_SYSTEM_PROMPT",
    "SYNTHESIS_USER_TEMPLATE",
]
